// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace APITest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Booking")]
    public partial class BookingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Booking.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Booking", "As a User, I must be able to find, add and clear a flight.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find all available flights today")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindAllAvailableFlightsToday()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find all available flights today", null, new string[] {
                        "booking"});
#line 5
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
  testRunner.Given("I find a flight from MNL to HKG using today\'s date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
  testRunner.Then("I should be able to see Success. in the response description", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find a flight using a past date")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindAFlightUsingAPastDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find a flight using a past date", null, new string[] {
                        "booking"});
#line 10
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
  testRunner.Given("I find a flight from MNL to HKG using past date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
  testRunner.Then("I should be able to see No fares found in the error detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find flights using a future date")]
        [NUnit.Framework.CategoryAttribute("booking")]
        [NUnit.Framework.TestCaseAttribute("MNL", "HKG", null)]
        [NUnit.Framework.TestCaseAttribute("SIN", "CEB", null)]
        public virtual void FindFlightsUsingAFutureDate(string departureStation, string arrivalStation, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "booking"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find flights using a future date", null, @__tags);
#line 15
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 16
  testRunner.Given(string.Format("I find a flight from {0} to {1} using future date", departureStation, arrivalStation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
  testRunner.Then("I should be able to see Success. in the response description", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find flights without an Arrival Station")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindFlightsWithoutAnArrivalStation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find flights without an Arrival Station", null, new string[] {
                        "booking"});
#line 25
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 26
  testRunner.Given("I find a flight from MNL to  using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
  testRunner.Then("I should be able to see The ArrivalStation field is required. in the error detail" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find flights without a Departure Station")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindFlightsWithoutADepartureStation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find flights without a Departure Station", null, new string[] {
                        "booking"});
#line 30
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 31
  testRunner.Given("I find a flight from  to CEB using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
  testRunner.Then("I should be able to see The DepartureStation field is required. in the error deta" +
                    "il", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find flights using an invalid Arrival Station")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindFlightsUsingAnInvalidArrivalStation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find flights using an invalid Arrival Station", null, new string[] {
                        "booking"});
#line 35
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 36
  testRunner.Given("I find a flight from XXX to KLO using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
  testRunner.Then("I should be able to see Station does not exist. in the error detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find flights using an invalid Departure Station")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindFlightsUsingAnInvalidDepartureStation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find flights using an invalid Departure Station", null, new string[] {
                        "booking"});
#line 40
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 41
  testRunner.Given("I find a flight from MNL to XYZ using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
  testRunner.Then("I should be able to see Station does not exist. in the error detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find flights using the same Destination and Arrival station")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void FindFlightsUsingTheSameDestinationAndArrivalStation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find flights using the same Destination and Arrival station", null, new string[] {
                        "booking"});
#line 45
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 46
  testRunner.Given("I find a flight from MNL to MNL using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
  testRunner.Then("I should be able to see No fares found in the error detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Booking Summary without any booked flight/s")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void GetBookingSummaryWithoutAnyBookedFlightS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Booking Summary without any booked flight/s", null, new string[] {
                        "booking"});
#line 50
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 51
  testRunner.Given("I login as a user without any booked flights", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
  testRunner.When("I get the Booking Summary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
  testRunner.Then("I should be able to see 204 in the Get Booking response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update passenger with flights")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void UpdatePassengerWithFlights()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update passenger with flights", null, new string[] {
                        "booking"});
#line 56
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 57
  testRunner.Given("I clear all booked flights of a user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
  testRunner.And("I add a flight from MNL to HKG using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
  testRunner.When("I update a passsenger\'s name with Automation and Tester", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
  testRunner.Then("I should see Success. in the Update response body", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update passenger without flights")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void UpdatePassengerWithoutFlights()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update passenger without flights", null, new string[] {
                        "booking"});
#line 63
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 64
  testRunner.Given("I clear all booked flights of a user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
  testRunner.When("I update a passsenger\'s name with Automation and Tester", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
  testRunner.Then("I should see No passenger booking data found, add flights first before updating p" +
                    "assenger information in the Update response body", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Book a flight")]
        [NUnit.Framework.CategoryAttribute("booking")]
        public virtual void BookAFlight()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Book a flight", null, new string[] {
                        "booking"});
#line 69
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 70
  testRunner.Given("I find a flight from MNL to HKG using future date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
  testRunner.When("I book the earliest flight", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
  testRunner.Then("I should be able to see my MNL to HKG Booking Summary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
